### ISSUE TITLE
Role syslog_ng fails with "IndexError: list index out of range" on "set systemd unit name" in check-mode

### ISSUE THREAD

**Issue by jorneilander** [bodsch/ansible-collection-core#16]
I can't get the role to work in `check-mode` and I dare not YOLO it.

Target environment: Debian 12
Environment:
```
❯ ansible --version
ansible [core 2.15.12]
  config file = <REDACTED>/Developer/git/dotfiles-ansible/ansible.cfg
  configured module search path = ['<REDACTED>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible
  ansible collection location = <REDACTED>/.ansible/collections:/usr/share/ansible/collections
  executable location = <REDACTED>/Developer/git/dotfiles-ansible/.venv/bin/ansible
  python version = 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] (<REDACTED>/Developer/git/dotfiles-ansible/.venv/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

```
TASK [bodsch.core.syslog_ng : set systemd unit name] ***********************************************************************************************************************************************************
task path: <REDACTED>/.ansible/collections/ansible_collections/bodsch/core/roles/syslog_ng/tasks/install.yml:17
[WARNING]: Skipping filter plugins in bodsch.core.dns'; an error occurred while loading: No module named 'dns'
The full traceback is:
Traceback (most recent call last):
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/executor/task_executor.py", line 529, in _execute
    self._task.post_validate(templar=templar)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/playbook/task.py", line 290, in post_validate
    super(Task, self).post_validate(templar)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/playbook/base.py", line 543, in post_validate
    value = method(attribute, getattr(self, name), templar)
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/playbook/task.py", line 298, in _post_validate_args
    args = templar.template(value)
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/template/__init__.py", line 797, in template
    d[k] = self.template(
           ~~~~~~~~~~~~~^
        variable[k],
        ^^^^^^^^^^^^
    ...<3 lines>...
        disable_lookups=disable_lookups,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/template/__init__.py", line 771, in template
    result = self.do_template(
        variable,
    ...<5 lines>...
        convert_data=convert_data,
    )
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/template/__init__.py", line 1015, in do_template
    res = myenv.concat(rf)
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/template/native_helpers.py", line 43, in ansible_eval_concat
    head = list(islice(nodes, 2))
  File "<template>", line 18, in root
  File "<REDACTED>/Developer/git/dotfiles-ansible/.venv/lib/python3.13/site-packages/ansible/template/__init__.py", line 295, in wrapper
    ret = func(*args, **kwargs)
  File "<REDACTED>/.ansible/collections/ansible_collections/bodsch/core/plugins/filter/syslog_ng.py", line 35, in get_service
    values = list(match.values())[0]
             ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
fatal: [helreginn]: FAILED! => changed=false
```

Since it's related to the preceding step, this is its (shortened) output:

```
❯ ansible -i inventory/hosts.yml -m ansible.builtin.service_facts helreginn
helreginn | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3",
        "services": {
            "NetworkManager.service": {
                "name": "NetworkManager.service",
                "source": "systemd",
                "state": "stopped",
                "status": "not-found"
            },
            "apparmor": {
                "name": "apparmor",
                "source": "sysv",
                "state": "running"
            },
            "apparmor.service": {
                "name": "apparmor.service",
                "source": "systemd",
                "state": "stopped",
                "status": "enabled"
            },
[...]
            },
            "user@.service": {
                "name": "user@.service",
                "source": "systemd",
                "state": "unknown",
                "status": "static"
            },
            "user@1000.service": {
                "name": "user@1000.service",
                "source": "systemd",
                "state": "running",
                "status": "active"
            },
            "x11-common.service": {
                "name": "x11-common.service",
                "source": "systemd",
                "state": "inactive",
                "status": "masked"
            }
        }
    },
    "changed": false
}
```

**Comment by bodsch** [comment]
Thanks for your issue!

I have implemented the possibility for a call with `--check` for the role `syslog_ng` and have written a corresponding test.

**Comment by jorneilander** [comment]
Can confirm, works as intended. Much appreciated!
